### ISSUE TITLE
Fails with newer versions of flake8

### ISSUE THREAD

**Issue by Goldziher** [python-formate/flake8-dunder-all#50]
Hi there, the code for the lib is no longer supported by flake8:

```text
There was a critical error during execution of Flake8:
plugin code for `flake8-dunder-all[DALL]` does not match ^[A-Z]{1,3}[0-9]{0,3}$
```

To reproduce, execute:

```yaml
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-dunder-all",
          ]
```
